---
- name: Inicializar o cluster de dados (se não existir)
  command: >
    {{ pg_bin_dir }}/initdb -D {{ pg_data_dir }}
  args:
    creates: "{{ pg_data_dir }}/PG_VERSION"
  become_user: "{{ pg_user }}"
