name: Deploy PostgreSQL via Ansible

on:
  workflow_dispatch: # Apenas execução manual

jobs:
  ansible-job:
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar o Playbook do Ansible
        run: |
          # Garanta que o caminho do seu playbook esteja correto
          ansible-playbook -i inventory/production playbooks/site.yml
