name: Uninstall PostgreSQL

on:
  workflow_dispatch: # Apenas execução manual

jobs:
  ansible-uninstall:
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Executar o Playbook de Desinstalação
        run: |
          # Ajuste o caminho do seu inventário conforme necessário
          ansible-playbook -i inventory/production playbooks/uninstall.yml
